"""init

Revision ID: 344cae1671b1
Revises:
Create Date: 2026-09-21 22:53:03.209145

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "344cae1671b1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guie_runs",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("owner", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("request_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("started_at", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.Text(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'timed_out', 'unknown')",
            name="guie_runs_status_check",
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    with op.batch_alter_table("guie_runs", schema=None) as batch_op:
        batch_op.create_index("guie_runs_queue", ["status", "created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guie_runs", schema=None) as batch_op:
        batch_op.drop_index("guie_runs_queue")

    op.drop_table("guie_runs")
    # ### end Alembic commands ###
